- name: Start a Docker Container
  hosts: Docker
  tasks:
    - name: Ensure directory exists for docker-compose file
      ansible.builtin.file:
        path: ~/firstContainer
        state: directory
        mode: '0755'

    - name: Create docker-compose file
      ansible.builtin.copy:
        dest: ~/firstContainer/docker-compose.yml
        content: |
          version: '3'
          services:
            web:
              image: nginx
              ports:
                - "80:80"

    - name: Start container using Docker Compose
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: ~/firstContainer
      ignore_errors: yes

    - name: Pause for 30 seconds to allow containers to stabilize
      ansible.builtin.pause:
        seconds: 30

    - name: Check container status
      ansible.builtin.shell: docker compose ps -q | xargs -n1 docker container inspect --format '{{ "{{" }} .State.Running {{ "}}" }}'
      args:
        chdir: ~/firstContainer
      register: container_status
      ignore_errors: yes
